### ISSUE TITLE
Why are LCC classes 34:36 only replaced for biomass >0 pixels?

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/Biomass_borealDataPrep#30]
`LandR::convertUnwantedLCC` function on runs on pixels for which B > 0, which means modelCover and modelBiomass may be fitted using different pixels (I found pixels with B = 0 and cover > 0).
I suggest converting classes in all pixels regardless of biomass:
```
  # availableCombinations <- unique(pixelCohortData[eval(rmZeroBiomassQuote),
  #                                                 .(speciesCode, initialEcoregionCode, pixelIndex)])
  availableCombinations <- unique(pixelCohortData[, .(speciesCode, initialEcoregionCode, pixelIndex)])
```

**Comment by achubaty** [comment]
this may now be moot / dealt with after reworking cohortData etc. @eliotmcintire can you confirm and close if appropriate?

**Comment by CeresBarros** [comment]
I believe we can close this.
