### ISSUE TITLE
Reasoning needed for establishment probability calculation

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/Biomass_borealDataPrep#31]
What is the ecological reasoning behind "integrating" `1-cover` over time (`successionTimeStep`), rather than the cover estimate itself?
It would be useful to have a comment before this line: 
`establishprobBySuccessionTimestep <- 1 - (1 - modelCover$pred)^P(sim)$successionTimestep`

Thanks :)

**Comment by achubaty** [comment]
i think we resolved this, but @CeresBarros can you please confirm and close?

**Comment by CeresBarros** [comment]
Yup all good :)
