### ISSUE TITLE
incorrect standAgeMapFilename

### ISSUE THREAD

**Issue by tati-micheletti** [PredictiveEcology/Biomass_borealDataPrep#41]
development branch: wrong standAgeMapFilename from commit "add standAgeMapFilename back in." (b73b313b62889d8f82e683d14dc067aa998dee25)

The filename added is from the previous version. The "correct" filename should be with 'v1'. However, I advise removing the targetFilename completely and letting prepInputs do its thing as we might update to newer versions in the future

**Comment by CeresBarros** [comment]
@tati-micheletti @achubaty I believe this has been resolved? can you confirm?

**Comment by tati-micheletti** [comment]
Looks like it. :) Thanks!
