### ISSUE TITLE
why use wrapper functions when objects are expected to be SpatRasters?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/Biomass_borealDataPrep#86]
working on the `terra-migration` branch, the metadata for the input/output objects has been updated to work with `SpatRaster`s instead of `RasterLayer`s. Yet, we are using wrapper functions e.g. `.compareRas()` instead of calling `compareGeom()` directly.

Is there a specific reason to use these wrappers (e.g., they perform additional operations/checks not done by the terra functions they wrap)?

**Comment by CeresBarros** [comment]
Yes backwards compatibility, as input object classes are not enforced
